import{i as b,a as q,S as I}from"./assets/vendor-Rdv7LHNr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const M=(s,e,a)=>{b[s]({title:e,message:a,timeout:2e3,progressBar:!1,position:"center"})},f=(s,e="")=>{M("error",e,s)},y=15,c=new URLSearchParams({key:"33588137-20261db95d6a52f088d4718c9",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:y});async function P(s){if(s.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return Promise.resolve(s.hits.map(e=>({webformatURL:e.webformatURL,largeImageURL:e.largeImageURL,tags:e.tags,likes:e.likes,views:e.views,comments:e.comments,downloads:e.downloads})))}const p=async(s,e)=>{c.set("q",s),c.set("page",e);const a=await q.get(`https://pixabay.com/api/?${c}`);return{images:await P(a.data),noMoreImages:a.data.totalHits<=e*y}},$=({webformatURL:s,largeImageURL:e,tags:a,likes:r,views:t,comments:o,downloads:l})=>`<li class="gallery-item">
  <a class="gallery-link" href="${e}">
    <img class="gallery-image" src="${s}" alt="${a}" />
    <div class="image-details">
       <div class="details-header">Likes</div>
        <div class="details-header">Views</div>
        <div class="details-header">Comments</div>
        <div class="details-header">Downloads</div>
        <div class="details-value">${r}</div>
        <div class="details-value">${t}</div>
        <div class="details-value">${o}</div>
        <div class="details-value">${l}</div>
      </div>
  </a>
</li>`,h=new I(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,animationSpeed:300,overlay:!0,overlayOpacity:.5});h.on("show.simplelightbox",function(){});h.on("closed.simplelightbox",function(){});const v=(s,e)=>{s.innerHTML+=e.map(a=>$(a)).join(""),h.refresh()},L=document.querySelector(".search-field"),m=document.querySelector("#top-loader"),d=document.querySelector(".gallery"),i=document.querySelector("#load-form"),n=document.querySelector("#bottom-loader"),w=document.querySelector("#no-results");let u=1,g="";document.querySelector("#search-form").addEventListener("submit",async s=>{s.preventDefault();const e=L.value.trim();if(e.length===0||e===g)return;d.innerHTML="",g=e,m.classList.remove("hidden");let a=!1;try{const r=await p(e,u);a=r.noMoreImages,v(d,r.images),i.classList.remove("hidden"),S()}catch(r){f(r.message),i.classList.add("hidden")}finally{m.classList.add("hidden")}a?(w.classList.remove("hidden"),n.classList.add("hidden"),i.classList.add("hidden")):m.classList.add("hidden")});i.addEventListener("submit",async s=>{s.preventDefault();const e=L.value.trim();if(e.length===0)return;u++,g=e,n.classList.remove("hidden"),i.classList.add("hidden");let a=!1;try{const r=await p(e,u);a=r.noMoreImages,v(d,r.images),S()}catch(r){f(r.message),d.innerHTML=""}a?(w.classList.remove("hidden"),n.classList.add("hidden"),i.classList.add("hidden")):(n.classList.add("hidden"),i.classList.remove("hidden"))});const S=()=>{const s=document.querySelector(".gallery-item");if(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}};
//# sourceMappingURL=index.js.map
