import{i as b,a as S,S as q}from"./assets/vendor-Rdv7LHNr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function a(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(s){if(s.ep)return;s.ep=!0;const o=a(s);fetch(s.href,o)}})();const P=(t,e,a)=>{b[t]({title:e,message:a,timeout:2e3,progressBar:!1,position:"center"})},h=(t,e="")=>{P("error",e,t)},f=15,l=new URLSearchParams({key:"33588137-20261db95d6a52f088d4718c9",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:f});async function I(t){if(t.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return Promise.resolve(t.hits.map(e=>({webformatURL:e.webformatURL,largeImageURL:e.largeImageURL,tags:e.tags,likes:e.likes,views:e.views,comments:e.comments,downloads:e.downloads})))}const M=async t=>await y(t,1),x=async t=>{const e=Number.parseInt(l.get("page"))+1;return await y(t,e)};async function y(t,e){l.set("q",t),l.set("page",e);const a=await S.get(`https://pixabay.com/api/?${l}`);return{images:await I(a.data),noMoreImages:a.data.totalHits<=e*f}}const $=({webformatURL:t,largeImageURL:e,tags:a,likes:r,views:s,comments:o,downloads:n})=>`<li class="gallery-item">
  <a class="gallery-link" href="${e}">
    <img class="gallery-image" src="${t}" alt="${a}" />
    <div class="image-details">
       <div class="details-header">Likes</div>
        <div class="details-header">Views</div>
        <div class="details-header">Comments</div>
        <div class="details-header">Downloads</div>
        <div class="details-value">${r}</div>
        <div class="details-value">${s}</div>
        <div class="details-value">${o}</div>
        <div class="details-value">${n}</div>
      </div>
  </a>
</li>`,g=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,animationSpeed:300,overlay:!0,overlayOpacity:.5});g.on("show.simplelightbox",function(){});g.on("closed.simplelightbox",function(){});const p=(t,e)=>{t.insertAdjacentHTML("beforeend",e.map(a=>$(a)).join("")),g.refresh()},v=document.querySelector(".search-field"),m=document.querySelector("#top-loader"),d=document.querySelector(".gallery"),i=document.querySelector("#load-form"),c=document.querySelector("#bottom-loader"),L=document.querySelector("#no-results");let u="";document.querySelector("#search-form").addEventListener("submit",async t=>{t.preventDefault();const e=v.value.trim();if(e.length===0||e===u)return;d.innerHTML="",u=e,m.classList.remove("hidden");let a=!1;try{const r=await M(e);a=r.noMoreImages,p(d,r.images),i.classList.remove("hidden"),w()}catch(r){h(r.message),i.classList.add("hidden")}finally{m.classList.add("hidden")}a?(L.classList.remove("hidden"),c.classList.add("hidden"),i.classList.add("hidden")):m.classList.add("hidden")});i.addEventListener("submit",async t=>{t.preventDefault();const e=v.value.trim();if(e.length===0)return;u=e,c.classList.remove("hidden"),i.classList.add("hidden");let a=!1;try{const r=await x(e);a=r.noMoreImages,p(d,r.images),w()}catch(r){h(r.message),d.innerHTML=""}a?(L.classList.remove("hidden"),c.classList.add("hidden"),i.classList.add("hidden")):(c.classList.add("hidden"),i.classList.remove("hidden"))});const w=()=>{const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}};
//# sourceMappingURL=index.js.map
